# Generated by Django 5.0.2 on 2024-04-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviegenre',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='movieperson',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movieperson',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personprofession',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='personprofession',
            name='profession_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='person',
            name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(to='movies_app.country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movies_app.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(default='film', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='persons',
            field=models.ManyToManyField(to='movies_app.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.ManyToManyField(to='movies_app.profession'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating_imdb',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating_kp',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='MovieCountry',
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
        migrations.DeleteModel(
            name='MoviePerson',
        ),
        migrations.DeleteModel(
            name='PersonProfession',
        ),
    ]
