# Generated by Django 5.0.2 on 2024-04-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
